-- =============================================================================
-- Call-A-Van legacy data import (Supabase + Webflow union)
-- Generated by call_a_van_backend/scripts/generateDataMigration.js
--
-- WHAT THIS DOES
--   1) DELETE all rows from driver_locations and drivers (admins UNTOUCHED)
--   2) INSERT merged driver profiles + location pins
--
-- RULES
--   - Union by email
--   - Supabase wins for password + approval
--   - Webflow fills missing profile fields
--   - Webflow Draft/Archived → is_approved = false (pending)
--   - driverlicense / Driver License → van_image_url
--   - Locations start offline (is_live=false); offline pin = coords when present
--   - Analytics NOT imported
--   - Admins NOT modified
--
-- Drivers to insert: 78
-- With legacy scrypt password: 78
-- Without login password (placeholder bcrypt; use forgot-password): 0
-- =============================================================================

BEGIN;

-- Flush existing driver data (keep admins)
DELETE FROM driver_locations;
DELETE FROM drivers;

-- Reset identity so IDs start cleanly at 1
ALTER SEQUENCE drivers_id_seq RESTART WITH 1;

-- adrianacovaci137@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
1, 'Filip scrap', '07424368078', 'adrianacovaci137@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAesV7pL4iD398HCJmj2H+gAPg0k0yW2/UnBoU4qGSFnIX7zQLcdwXrv4oQB6faWBzraGfKGI4brpxTOX81Xhj8q54UM+g8WYRFl9qPeZWTCM', 'Filip scrap', 'Glasgow', 'Van', '', '["Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-02T13:42:08.906Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777729327085-inbound6196284230241330307.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777729327318-inbound5832742087900537578.jpg'
);

-- agvanandmanserviceglasgow@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
2, 'agvanandmanserviceglasgow', '0000000000', 'agvanandmanserviceglasgow@gmail.com', 'c2NyeXB0AA4AAAAIAAAAATc+GIKLR3TyRcqyMPbHJNwL+Eh5uOJ4EJ7Av2xIWypJX0Y0T38YjmIg6DlLa5JodhPhzb0vF0DzcnZy+EkKPJD+FjFGQB26/nmN1jbPcDa6', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-23T21:36:14.958Z', NULL, NULL
);

-- agvanserviceglasgow@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
3, 'AG Van and Man Service Glasgow', '07447512000', 'agvanserviceglasgow@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAcwtL3P1ONoNw7Ds5bpd3xtyxaHEkebKKQeMfuNMumdpe/sQWHN/YbJbasN+DUHmsP9mraRWdEud7JC6q+z41O/dtaETgzt3+iwGAENs4PsW', 'AG Van and Man Service Glasgow', 'Glasgow', 'Peugeot boxer l3 h2', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-04-23T21:41:31.027Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
3, 55.8691016, -4.1859263, 55.8691016, -4.1859263, FALSE, FALSE, NOW()
);

-- ahmadshaukat328@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
4, 'ahmad new 1', '5161577878', 'ahmadshaukat328@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAQo1QyW6QeOhGayM3V93wSksf5F63GHb8ZlARW49+AsUV9w/I9FHNemb1Mb0g1yKxj/EfUJk/mWCv+FwHWTojyxcNoJ0NFkW6Wa7vSpGidFr', 'test', 'test', 'test', 'test', '["Single Item Transport","Storage Moves"]'::jsonb, TRUE, FALSE, '2026-05-19T16:41:08.190Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
4, 31.4633207, 74.389293, 31.4633207, 74.389293, FALSE, FALSE, NOW()
);

-- akpremiermoves@hotmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
5, 'AK PREMIER MOVES', '07947569386', 'akpremiermoves@hotmail.com', 'c2NyeXB0AA4AAAAIAAAAASXv2mnVNb+8tLKZhc8YGuI2gPalzqZSDNH+S9gpEv5DXnDKTwcPl1E777WCqU95buj9+3IPbYiX7DuXInelgynkqf4CGC6Zb9yk48EnWnBK', 'Ak premier moves', 'Glasgow', 'Long wheel base', 'Man and van covering central Glasgow / long distance', '["Single Item Transport","Furniture Collection / Delivery","Small Moves / Student Moves","Storage Moves","House Removals"]'::jsonb, TRUE, FALSE, '2026-04-23T12:11:45.585Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776946303647-IMG_9814.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776946304007-0D89DE22-20A8-4F49-A39A-0E177F9516FF.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
5, 55.8513188592036, -4.30342440571838, 55.8513188592036, -4.30342440571838, FALSE, FALSE, NOW()
);

-- andrewrussell90@hotmail.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
6, 'Andrew Russell', '07784355653', 'andrewrussell90@hotmail.co.uk', 'c2NyeXB0AA4AAAAIAAAAAdkaWsADy7UomkS+MXMFDNRanZIlTUPZyausI/Dm2GkkXQug/L7LTcXdTZTVYBkFZEYO1SDZPBQ72RZGZvT1r2jpg3MpAE4R/OA8FRFyMV2J', 'A&L RUSSELL LOGISTICS', 'Ml14dq', 'Lowloader box van', 'Been in the delivery industry for 7 years now and ave still got the drive and passion to get the job done with a smile of a customer', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-05-31T15:41:00.919Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1780242058861-187695.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1780242059463-187843.jpg'
);

-- anthonymcfadyen26@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
7, 'Tony mcfadyen', '07990354680', 'anthonymcfadyen26@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAe63JNMtunG5uZVnJSFi4wGELKXZ21zBGIPAYioOfCdl+sX+v0iXDUB+4gAjzJYf8SGk+jeGRxPVVllZDKqfa5OKAUIu5zXYEZ6iFXzMBSr0', 'Cheap man with van removals or pick ups', 'Scotland', 'Citroën relay lwb', 'We been doing this 14 years experience and fully insured with blankets and straps', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-20T16:22:12.508Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779294130356-inbound6098511446178892785.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779294130585-inbound1990647809126092148.jpg'
);

-- anwarulhaqch8002@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
8, 'Anwar ul haq', '07903277799', 'anwarulhaqch8002@gmail.com', 'c2NyeXB0AA4AAAAIAAAAARmGqQA5zs5TRFvMgn5ktZfYO5PjJn7NRKLgDZaTjsha6DCJGLYYGie/i6bpy5kmVKJeXNGTwkY7LuOTNkzfXT0x+FKpZWOWrr0itXGdIdyb', 'AUH logistics', 'Irvine Ayrshire', 'Ford transit', 'Recently am doing work with Cx', '["Single Item Transport","Furniture Collection / Delivery"]'::jsonb, FALSE, FALSE, '2026-08-12T21:30:57.127Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786570255766-IMG_0325.jpeg', NULL
);

-- asjdkas@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
9, 'asjdkas', '0000000000', 'asjdkas@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAfDTbbiaMzoUcqkd3QjQ+fi5VgslbZlQOHIirHNcbIyA2GWmGgyIZL+PbAw2XMWUcWNF/NTtsNr9hZHUqIW5ric53PWq/krPGLbbZjSMYS8k', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T06:56:50.887Z', NULL, NULL
);

-- ayzallogisticsuk@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
10, 'Muhammad Asghar', '07931933396', 'ayzallogisticsuk@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAY+Uh5AUJMn9AGIoZ/9dzp8YXPBmwTsefUyz+oq/UcYdIv9z/gVa7AezgASj6n/5infBJLzs9wVzfdYtNaJQqbpOElBM5a+pYfpOxST0+VSp', 'Ayzal Logistics Ltd', 'Ml20JH', 'XLWB Vans', 'Hi this is Ayzal Logistics A courier delivery company also working for House Removals Furniture transfers Single Item Transport can do local and national deliveries', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-05-19T00:44:00.141Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779151438050-IMG_8563.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779151438630-IMG_8534.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
10, 55.7678705320379, -3.92769644352402, 55.7678705320379, -3.92769644352402, FALSE, FALSE, NOW()
);

-- betvshi@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
11, 'Sarvar ebrahim', '07463636366', 'betvshi@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAfdNbeQgWXTVLih1+Tn3W5/pTFl58zY5X+vEgARxDCNJJBkfLuN3DyJHJZlCU4D5vugquwWKrALqOD5bplypzz8h2gnzE2F+2ybD+qgEUqRl', 'Eml removal', 'Glasgow', 'Luton van', 'Professional in house removal', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-10T21:45:29.766Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778449527766-inbound4297394409246310797.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778449528227-inbound3465498063659982355.jpg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
11, 55.9513188592036, -3.83220637462825, 55.9513188592036, -3.83220637462825, FALSE, FALSE, NOW()
);

-- bigpaulcallaghan@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
12, 'Paul callaghan', '07950517565', 'bigpaulcallaghan@gmail.com', 'c2NyeXB0AA4AAAAIAAAAASEFTgoU1qqVOv6XnQnAvPbO8kXt9lrWMofNRx+5Xm/h3E/WkFiPs6nVrE86UWcqKI6m82XHbdBwopCUDMWD9sWylwa+rfE7Ktny0Lxqrplf', 'Clydevan', 'Glasgow', 'Mercedes benz sprinter long wheel base', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-17T15:13:23.892Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- bridgetlawrence2018@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
13, 'Peter', '07443055863', 'bridgetlawrence2018@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZ6DXccOIRxT7ltMCm4JkUGypzMp9xPqCSU1BvIEsoFiOwt5pBrWm/nYafUFFBIuBxsvDQkWagE3TPQgNtAiOo4PeKDAQyGQladfsf17dmgl', 'Rubbish masters', 'Glasgow', 'Van', '', '["Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-29T07:28:09.600Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- cccremovals@hotmail.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
14, 'Ccc removals', '07899027425', 'cccremovals@hotmail.co.uk', 'c2NyeXB0AA4AAAAIAAAAAZl5QyRBfjTnQbfwOgaBxh9JTMGh/sN1u5JaGA9hmYhj+6x0gVhaJ5WsL7tUZznjmiPf/Fj5GNPctuGEmNUoDJsGUdKr2Pzla1fMHehY6Lwh', 'Ccc removals', 'Paisley/glasgow', 'Luton van', '', '["Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-04-21T10:15:53.243Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
14, 55.4613188595036, -4.33220637462825, 55.4613188595036, -4.33220637462825, FALSE, FALSE, NOW()
);

-- chris5starremovals@outlook.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
15, 'Chris Hendrie', '07759122693', 'chris5starremovals@outlook.com', 'c2NyeXB0AA4AAAAIAAAAAf7p2mEpZRwB2SiwRPP1Ut8iWJ11ophU2+sUoeBT+SgZNBsnmk/e68uzMSYP1u12ksJN1YGWzQ3zDDRedSk7QR/Bkt7hfTuVugU05CBU7l/A', 'Chris 5 Star Van Man Removals', 'Glasgow', 'Long Wheel Base Van', 'Over 500 5 star google reviews, Reliable, professional man-and-van service based in Glasgow, covering Scotland and the UK.', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-08-27T17:34:35.680Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1787852073196-IMG_8537.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1787852073918-IMG_8537.jpeg'
);

-- cjpw2020@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
16, 'cjpw2020', '0000000000', 'cjpw2020@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZgKSAc2UafySLmNs25BDDr3RPtnUcXNDLAS0nzzVQSLZ17KfmZSs/mCdSNWlqMUyxVP4CoKL8YoDK0R5NC6XhI0EZ+y3LHTCKnkCYApC957', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-05-17T16:33:50.959Z', NULL, NULL
);

-- colinwilliams30@live.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
17, 'Colin Williams', '07597861995', 'colinwilliams30@live.co.uk', 'c2NyeXB0AA4AAAAIAAAAAdqDKPJ300HXp3DppEr2HKQt/O74eSn98x3FDYgsc60Da+73crIGUj8ID2M40Grh3BMqFdBzdgT8UvNRbknyiwtNAuMLfdoPKTTqrC6bZqwM', 'S&C services', 'Glasgow', 'Van', 'Have over 9 years experience from single items too full house removals throughout Scotland and England', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-17T19:51:25.738Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779732741696-IMG_4334.jpeg', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
17, 55.8836310776471, -4.28016445599895, 55.8836310776471, -4.28016445599895, FALSE, FALSE, NOW()
);

-- contact@theremovalkings.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
18, 'The Removal Kings', '07493335550', 'contact@theremovalkings.com', 'c2NyeXB0AA4AAAAIAAAAAad0txwht6d8Lw5tHhYOtiAa5mg6EECxfqhQLJjWRivzTdwQGJGVA3gfTtB2A6TF6H1/K+VVIOeYZm/B2pXyme4BHGPhoEORb04MKo22/TUc', 'The Removal Kings', 'Glagsow', 'Low loader luton', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-19T17:57:39.504Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779213457580-IMG_1593.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779213458085-7138B06A-B329-489B-BB2C-4D9258ABB98E.png'
);

-- danyo1987@live.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
19, 'Glasgow Man With A Van', '07984537071', 'danyo1987@live.co.uk', 'c2NyeXB0AA4AAAAIAAAAAcZlAoFsYuKSb1msJCN8FSsBGoQncBXmA5YF1kJKgSPpFYzTgsQZM7UUfx3eSNweOzaSXDuNxMRg9eHHErowi2VbmRNwOKuhrl/YBI++fk46', 'Glasgow Man With A Van', 'Glasgow', 'Mercedes Sprinter Long Wheel Base', 'Home removals & SEPA registered waste Management. We have 3X LWB vans', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-15T17:29:28.202Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778866166390-1000151480.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778866166974-1000151484.jpg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
19, 55.8691016, -4.1859263, 55.8691016, -4.1859263, FALSE, FALSE, NOW()
);

-- darren@nudgeexchange.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
20, 'darren', '0000000000', 'darren@nudgeexchange.com', 'c2NyeXB0AA4AAAAIAAAAAf3WAWEbmFYioKlyjG9yiEGOrmD46l2l+uVCpBvmOnMXxbnQ6G2Nnf2Q9CtAhBoCUX1cr3df53X8klDkvtu0pQciXjNdinOsOq5P3oHJ0Vh7', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-03-26T19:54:16.427Z', NULL, NULL
);

-- davey@dwppcare.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
21, 'davey', '0000000000', 'davey@dwppcare.com', 'c2NyeXB0AA4AAAAIAAAAAfnBQyC2bp9l6O5GkX29wgapM9Rm6qSagNxPnObzKZzaXTmZqVZy65jMaoTsO9WmKsKLkEVUf41RemLByGX850yDZ78Nq2h+dJR4o5JFuXp9', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-10T15:44:35.897Z', NULL, NULL
);

-- daveyw@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
22, 'Davey W', '07307355506', 'daveyw@gmail.com', 'c2NyeXB0AA4AAAAIAAAAARpYJxRJCPhJZ+g7C39hvSxEG69/w7PIr2NjQF6lBLPOWwdw9sYL1Oxfi0weR0tnKj+5WGFKWAtfm0IkZCNnFHdbf94fyg+02Q4CJ5sm/Lck', 'DW Precision Property Care', 'Glasgow/Southside', 'Ford Transit Custom', '', '["Waste / Disposal Runs","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-04-28T09:59:35.699Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
22, 55.7696530511184, -4.31436720830351, 55.7696530511184, -4.31436720830351, FALSE, FALSE, NOW()
);

-- deliveredbysk@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
23, 'Paul singh', '07377812140', 'deliveredbysk@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAZRbfjrQdEtv6VDR/wRuoG2+i1kfeYREP42MaxDGTT/T8mwbha6POG0EJcrEVH0ZX0CMOc8De+//v/MqaUru5xzLkAFjpnHBse2d2goV4mEP', 'Delivered By Singh and Kaur', 'Glasgow', 'Lwb sprinter', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-05-20T16:22:39.459Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- dg@yahoo.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
24, 'DG Removals', '07507182152', 'dg@yahoo.co.uk', 'c2NyeXB0AA4AAAAIAAAAAd9r47euogOMp4NjP2sv/RPlEJHEUvpVh5NQEIBqc513szA/am34NoAtT1RufUqjOhd7rDLKEzm9PneQa0O2MpbWjkwXQz44oOL9QtbA/J1W', 'DG removals', 'Southide Glasgow', 'Luton Van With Tail Lift', 'Reliable man with a van covering Glasgow Southside. Quick, local moves, single items, furniture pickups and house clearances. Friendly, flexible and easy to deal with.', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-03-27T18:02:36.976Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778868677628-Image%201.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1775646223848-Image.png'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
24, 55.8469037579117, -4.41111145330968, 55.8469037579117, -4.41111145330968, FALSE, FALSE, NOW()
);

-- divbigger@yahoo.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
25, 'divbigger', '0000000000', 'divbigger@yahoo.co.uk', 'c2NyeXB0AA4AAAAIAAAAARrnB9QE9H6UR1BbF0FBvTI+EBkyhIv/V9YtVRC9yl9ph4M3ZmgfxfkTeN/VJYGcibhyio51TWOhERNq+8AjUJhjPGPtmXgOEWaPSkNua6KR', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-03-31T18:55:25.701Z', NULL, NULL
);

-- dlkg@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
26, 'dlkg', '0000000000', 'dlkg@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAesCumJ76UuAxtkYj+C/qHUKBTnc87/kRC50Y+haEQqXPb+juTE1zgEJZDNZ7sr4TzI6ZBjZPhVCf1ok7B/lnPA7/ASuHsswcgbfJE3LzeAo', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-06T21:03:24.181Z', NULL, NULL
);

-- firstlast@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
27, 'firstlast', '0000000000', 'firstlast@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAXIzOjOHNp0bysPrPfY0eEYsNBOPgS8rpCzgFiX9wfTCTnOZHqMtTKIv7ys4suJIG0JYzSUCH0JQhU7u/W3r2mG9z3qrrz1pfdZklvEpKel/', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T06:53:22.025Z', NULL, NULL
);

-- flemingdarren554@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
28, 'Darren Fleming', '07391698472', 'flemingdarren554@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAXr28zD6Dnm25ePjDbV72r2U359G0UTs2cfBiWQkKbXdSqawkvgHiiOSmH/w4UMGisjIan1q6ifzeyvwVM5rVB0xWcMsqXAmEuXRbcIMj5CT', 'Stress free uplifts', 'Glasgow', 'Long wheel base', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-19T13:24:26.302Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- garya211281@icloud.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
29, 'Gary Anderson', '07598905437', 'garya211281@icloud.com', 'c2NyeXB0AA4AAAAIAAAAAcwdRjsZ8i+7K9y7wNRowi8GdigFInoyOkOYYnaGOmYWUGa3/IK3JJRfp0Ux/T92JY/NLiDbYgnnYxvUwj1gWuuTa85fhqGPdzZdWRwoMUEI', 'Gary Anderson', 'Glasgow', 'Small van', '', '["Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-07-12T21:40:57.617Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- gillgalloway@me.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
30, 'gillgalloway', '0000000000', 'gillgalloway@me.com', 'c2NyeXB0AA4AAAAIAAAAASRmVre4Qovvp0X+NmZWuv2zq+fkBk5ckszKlsiekEtOns9SPaBS5TR6xHl0H1Yku7JhkhHNX53lbMc+PaLuCKmWdrkeCK+2uHSopqDXVvWm', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-03-26T19:50:53.030Z', NULL, NULL
);

-- haqanwarul145@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
31, 'Anwar Ul Haq', '07903277799', 'haqanwarul145@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAaLoVwTseoek8wXpcln39iSLciaJv8tVnwdxv8qbIoRHO1jJGFXx+/lb5wejkFh2faMUw4YgMBVtu4s/M4fO/WU7PYf8OZAkQuh4gYyfI492', 'AUH logistics Ltd', 'Irvine ayrshire', 'Ford transit', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-08-13T10:04:54.339Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786615492650-IMG_0325.jpeg', NULL
);

-- hehecxbmbzm@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
32, 'hehecxbmbzm', '0000000000', 'hehecxbmbzm@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAVF6VxnT9j49epZQY5Q7BKjTyAOfNcjP7hX0kvPVlRGVxyCOc+Jb0nEcBBtvkWs/o41F3+VR0uSC6up1DycOSg4ImddrojDmwEQ+ELcNXHs7', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T07:34:51.381Z', NULL, NULL
);

-- hiignis@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
33, 'hiignis', '0000000000', 'hiignis@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAb0+oirSL1I8Ya+oP8nKMtpGK4sM+A1WgEeZZ7BMVppKH4m/IicyvphygcYPlX3kR/D/bvfdhh9mpSaZHOsKCNKIskobHlAeiLsW2EPzhRIg', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T07:37:55.854Z', NULL, NULL
);

-- hiuser@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
34, 'hiuser', '0000000000', 'hiuser@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAcY1Ny3tbX7XaRuQu8reYGnOXYsXGs0Zq28uBi/BIM9mOm4v7Hh6zcG6Cuo5QMYZ0g3is/SMFBQFyxvAGXPnLusYRYXGSVlI/5uQKiDD9N5D', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T06:45:54.870Z', NULL, NULL
);

-- hollyshankland@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
35, 'hollyshankland', '0000000000', 'hollyshankland@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAUZOEUxAVCwcP5WnRQ/JuHTC8kZYB2EplRFZHWGL7fr23+nxJw01wOPgw9oBuDBXHJMb2NnY9mu+3AIbg82qiBqDyJ1P17+TdTk9pgZY1MlS', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-05-17T08:24:54.919Z', NULL, NULL
);

-- hollyshankland1@icloud.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
36, 'hollyshankland1', '0000000000', 'hollyshankland1@icloud.com', 'c2NyeXB0AA4AAAAIAAAAARO7DWDEw4a3oTLGfEoPSvYbRpUuLT7EKAR5trXqQYwAq6wrMpaTnMG5AW6Jcd979cAxGLGrzU5oYjP2xiKxBrFh1LEjg8oOHFfPVn9x6bSQ', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-03-26T20:28:57.518Z', NULL, NULL
);

-- hs@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
37, 'Jj yy', '07526524446', 'hs@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAbOqtm1aTOyRqKYS0StG1683ETi68JzjlRr/7W7KI2FldXxUD2vaHbuRoD+nL3+2IwiU10Y/rsEEtoabgnzebEJbXvZoCEA6/fmZaCSPToPN', 'Ggdd', 'Ffs', 'Cvvh', 'Cfff', '["House Removals","Single Item Transport","Storage Moves"]'::jsonb, FALSE, FALSE, '2026-08-13T09:21:55.892Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- jackmorton459@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
38, 'Jack morton', '07754924336', 'jackmorton459@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAdaR+20YJ/b5qOFOWm7Utj6vCOYIbBbFZFqlr3oAP6V+59nO79v7d4xroeaW3Th6sjbMME/QH8WD/preVTdHlEYtqTBk+ZeCVUNmFTuSytlh', 'SCOTVAN', 'FK2 0DQ', 'Vauxhall Vivaro Standard Wheel Base', '', '["Waste / Disposal Runs","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-12T13:03:11.292Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- jamestevenson1983@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
39, 'JnR man and van', '07391453557', 'jamestevenson1983@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAexTIX2s71XvNo+DWRemECtjeZY1fTnyw1UhKcx1NKg38injiIbrjTSuZsTaZF3yN7mZ1lRT9M7xSc7NFTJWCYDgFH069GCltj18LOrKGuQ9', 'James Stevenson', 'G33', 'Transit long wheelbase high roof top', '07391453557', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-13T07:03:45.293Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779177587858-9F789597-8704-4D75-BF62-5E88B7504F51.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778655822282-IMG_4520.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
39, 55.8635513661152, -4.43011470953864, 55.8635513661152, -4.43011470953864, FALSE, FALSE, NOW()
);

-- jamie@sc-sameday.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
40, 'Jamie Stewart', '07498736758', 'jamie@sc-sameday.co.uk', 'c2NyeXB0AA4AAAAIAAAAASdYhsZQ9tF1jw60yDeHAeZdLOpLB1psZX9XuNCAdSGFMSH2dMo0mRFmzSNWEpwXF2tnuy+8jmySiCDT8R7KWRGJX+wStfyzzD9Z414CZJdG', 'SC Sameday Ltd', 'ML3', '4 XLWB Sprinter', 'Kitchen delivery Specialist', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-05-19T12:40:16.051Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779194414295-DF4C5795-7697-4D79-B65F-8721651B986E.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779194414700-IMG_5198.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
40, 55.7753758791624, -4.09140172783254, 55.7753758791624, -4.09140172783254, FALSE, FALSE, NOW()
);

-- joegilchrist30@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
41, 'Joseph Gilchrist', '07508371886', 'joegilchrist30@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAUhwAQrr//ZxnV2bxjPq/ugC7cnB7DhiLSewwt2wZgfKWfDqbt1dfeh6ed60Y6IJCaaxaHviwWc1d/16125eDLFMcLc0+ukNLMLqE1+tO/gV', 'The Baldy VanMan', 'Clydebank', 'Renault Traffic', 'Baldy VanMan offering competitive legitimate van and man duties!', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-14T15:55:03.681Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778774101935-inbound3625086665266045099.jpg', NULL
);

-- john2@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
42, 'john2', '0000000000', 'john2@gmail.com', 'c2NyeXB0AA4AAAAIAAAAATZvDb7a9sRTBTmjmWWDOJ6eFrQCOQ15sc5VtBY89frOYocBSQTfXYEEp6qWDqa5PoxSLO24wOaU+ZfmIdscSUhjd7XkvXParCWhfQgSv+hg', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-08T07:43:11.373Z', NULL, NULL
);

-- johnpaulfitzgerald93@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
43, 'F3 Solutions', '07866149244', 'johnpaulfitzgerald93@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAYxadBpfP6F8eT+6gdck8mJwcr8WaHM9roQV7wA93YXsCkDGlM41xQaHoFalIqCblFrTRCSCg/mWyMALeHlKD+Ktr+8gc3xWp4Rc74u0hcRP', 'F3 Solutions', 'Glasgow', 'Sprinter', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-14T19:28:17.603Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
43, 55.8868148, -4.2559491, 55.8868148, -4.2559491, FALSE, FALSE, NOW()
);

-- jordan@jordansvanservices.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
44, 'Jordan Ayre', '07544912030', 'jordan@jordansvanservices.co.uk', 'c2NyeXB0AA4AAAAIAAAAAWNGS8Uo5Yfq0V6j/OXDGQ02+MKPYarjZjZYRz6+jpWhqdUPnb9oNF8wsZ6Emtf0Ty1Hjra4eY2xJWEZOWSTkiWPXFFZQSuGEe4MCPi7HJqt', 'Jordan''s Van Services', 'Lanark', 'Luton', '', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-13T12:42:58.470Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778676176349-3d6103ae-60c7-470f-b623-d1738660731f-1_all_26937.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778676177065-1000040315.jpg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
44, 55.6813334, -3.7667755, 55.6813334, -3.7667755, FALSE, FALSE, NOW()
);

-- kevbonini1@icloud.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
45, 'Kevin B', '07882134840', 'kevbonini1@icloud.com', 'c2NyeXB0AA4AAAAIAAAAAdYPO0L4BHQcYYJgGlCYecVW3k0AHIH3V23g9GHoeI8AOd0EOfLURCsgaVCX2cUc8D9+5IGSevHn1Y1pnfXEZ4TRgm+W7+huEIu+kA3sY4hS', 'Glas24/7gow man & van and dog transport', 'G34 9Qf', 'Vauxhall movano long wheel base', 'Reliable van service and animal transport in Easterhouse available 24/7', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-17T07:19:13.662Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779002351920-IMG_1406.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779002352170-IMG_1062.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
45, 55.8737205043744, -4.12795718696813, 55.8737205043744, -4.12795718696813, FALSE, FALSE, NOW()
);

-- liam_conway@yahoo.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
46, 'Liams Removals', '07929440190', 'liam_conway@yahoo.co.uk', 'c2NyeXB0AA4AAAAIAAAAAayb+8W+mROQpReAXhZwFRiP/Ld+GMbAF3lj25HNNlgIBPb2eIFTbmb+/aFgvfvMPZHRr4XsDq+FNdaG1ndHOeTtqrwGjbpFK6brlq6EHwPY', 'Liams Removals', 'G52', 'Vauxhall Movano MWB', 'Operating last 15 years proving friendly removal service', '["House Removals","Small Moves / Student Moves","Storage Moves","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-01T19:02:23.522Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777662141573-20241118_115626.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777662142134-20250514_151815.jpg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
46, 55.8427271806175, -4.35744027451369, 55.8427271806175, -4.35744027451369, FALSE, FALSE, NOW()
);

-- malikfoods10@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
47, 'Umair Shehzad', '07762113956', 'malikfoods10@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAdnnGqUlx1SUk/occaeAofG5jiiDGlYSqkHUdgmeaXhZYH6g+bA4+sv2NPlyDPUt1V9LNUf/HMr+N1CjWKK0OVaMxASKU+7GQGpzWkIAy4Xe', 'Malik LTD', 'G521ST glasgow', 'Low lowder luton van', 'Hi my slef Umair and i live in Glasgow,work as a van driver in DX and i am available on weekends thanks', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-06-15T19:46:13.082Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781552771169-IMG_6104.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781552771883-IMG_6104.jpeg'
);

-- markmoss2310@googlemail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
48, 'Mark moss', '07494866644', 'markmoss2310@googlemail.com', 'c2NyeXB0AA4AAAAIAAAAAUynCmnYgAn+CSZAZTh9oHzuiy6vU0SGHPYblrZYHEoPQAeU9DBIIHiRJAedvxASfwGYmkeosEgpZ0Ue/y0FMK6IpM+9qNKAR8Eh1OCIfZgi', 'Spark couriers', 'ML5 4PA', 'Mercedes sprinter lwb', 'Hi I have experience in removals storage moves furniture collection or delivery''s small items moved and delivered i can also remove waste', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-17T21:09:47.420Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- mcletchieian0@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
49, 'Ian Mcletchie', '07727145358', 'mcletchieian0@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAca2WjOAcjyDIlI0epMGkqAzTFh9qG7huCLtZ6lm1c/nXukjKcx6Zgj5RtBdA3HsAvN+3Q7KRLs+pvnu7NywdGyYGxxdeHOw7oy0ErNWmVQy', 'Mcl waste removal', 'Glasgow', 'Vw crafter extended wheel base', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-08-20T21:44:12.538Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- mcveyjp@hotmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
50, 'John p p McVey', '07799735893', 'mcveyjp@hotmail.com', 'c2NyeXB0AA4AAAAIAAAAAcIScydnIo6/wTcvqtdse4Hzp1gW6I+XbK9Y/G/hB9n1ku8cILOENYgdXpa46NRaQ3tbjyHnpgq+u9tEdCE7FmYFhPfh6jKYwrvFJMrPwbS4', 'John P McVey Saltire Removals', 'G50NA', 'Daf 10 tonne ridge box', '40 yrs driver owner operator 20 own removals company', '["Single Item Transport","Furniture Collection / Delivery","Storage Moves","Waste / Disposal Runs","House Removals","Small Moves / Student Moves"]'::jsonb, FALSE, FALSE, '2026-04-22T14:51:19.425Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776869476340-2ab9032d-5ec2-498f-94b6-7e2f16c98883-1_all_161.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776869477666-1000038122.jpg'
);

-- mearnsremovalsltd@hotmail.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
51, 'Scott mcculloch', '07584858861', 'mearnsremovalsltd@hotmail.co.uk', 'c2NyeXB0AA4AAAAIAAAAAfgQyY1PBazgMTWCT7aS4yhY1mHcmpm2UcdPxwilJzSzTr+88en6IbE3/dxfxXdmm1SvsSEF5bA5a1sQAVr6yQ2x2nvL2+/sf1oCLRShlqrJ', 'Mearns removals ltd', 'Irvine', 'Ford transit tipper', '', '["Waste / Disposal Runs"]'::jsonb, FALSE, FALSE, '2026-08-12T13:57:21.164Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786543039790-25876.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786543040001-37264.jpg'
);

-- mr_markovnik@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
52, 'Mr Marek Dzisevic', '07492200890', 'mr_markovnik@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAVht0Nesn5+wy78yhg0d4gRlUiQ2DSJxD/UPnlOJv8xSiLvzTCRFi0NwZwJObk/awFYhej5LHXOHyWGvc0nyAhe8WJtT89DG6sBcx+8zreXr', 'Mr Marek Dzisevic', 'PA1 2FA', 'Lwb van', 'Courier', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-17T08:48:46.521Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- nas_9@msn.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
53, 'Jason Morgan', '07525140511', 'nas_9@msn.com', 'c2NyeXB0AA4AAAAIAAAAAVH6hDm/PyUfVALuGkyl9sMgzWdgYA5CJ93bcCrRHJ2XDl1MCYErT3q/RtaIPjT8/NmBnsAQ/2tAoRtJVk0rFhPmsQ/Lqprk6fORObyTlqwU', 'Trash Monster', 'Glasgow', 'Crafter and 2x sprinters', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-15T08:59:07.656Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778835544500-inbound5871355124603805196.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778835544980-inbound8677270529874360865.jpg'
);

-- opovic666@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
54, 'Slav', '07729289444', 'opovic666@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAdx6MYKY+1p8FbMgYoE9aMLUCKmLrIT59ZbHQ/Zk3AV6zcbcuqc+StT35bk35R2GDixTQAacHWUfy3JFr4ZO8aef2BEvQH508Nt/euvyR13h', 'Slav', 'Motherwell', 'Van medium wheel base.', 'Professional Delivery Driver', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-16T13:35:36.761Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778938534937-IMG_1189.jpeg', NULL
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
54, 55.8025783564662, -3.96965049726488, 55.8025783564662, -3.96965049726488, FALSE, FALSE, NOW()
);

-- qsg@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
55, 'qsg', '0000000000', 'qsg@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAaxBH/sVsB02VVyYN+X4JozG73k/mLr1GhrYRLJmv0rhS8C5l/B+UYbRiXn8PLqwDYL9c2RorswSnP4uwdbGDrYeN6A8T0ASyBBWeaMj5kw1', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-22T15:36:42.561Z', NULL, NULL
);

-- reillyanton78@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
56, 'Anthony Reilly', '07851972360', 'reillyanton78@gmail.com', 'c2NyeXB0AA4AAAAIAAAAASKTSUauLsJkUEtXcfkqeFBM4hB6yATuOUTJ25T57b6008SBLFk6S9EkfpAjhnA22T4Emt8e+GzY0qJiKF/0h+ZjwcHAkSedDiVW+mRYZLwH', 'Reillys Removals', 'G33 1SE', 'Mercedes long wheel base sprinter', '', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-17T07:22:09.210Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779002526518-inbound5425683546120487242.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779002526932-inbound8953715176794911860.jpg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
56, 55.8540641, -4.5096019, 55.8540641, -4.5096019, FALSE, FALSE, NOW()
);

-- rightwayremovalsltd@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
57, 'Reece Ferguson', 'Reece Ferguson', 'rightwayremovalsltd@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAVpVCaAQ9+6lt0a6EmHj9Cg4T+2Q89bPams0/XdKOz+ezMAJxRz/TTLtZWu1Dlk8NXt2gZpv+hcP3IJO0NF6n1qyuU/00iYMAkBTdBQls8Du', 'Reece Ferguson', 'G51 4FA', 'Reece Ferguson', '07782873252', '["House Removals","Single Item Transport","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-08-17T12:40:09.633Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786970407791-P1030478.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1786970408298-IMG_5871.jpeg'
);

-- robert.andersontug@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
58, 'robert anderson', '07491738350', 'robert.andersontug@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZAPBgb/B1j3vSCcKLaVud7MbfYs4StSOp5mpbm2D6bObCwMWbxaSEEGYdcq0er5aPeTgus8njDD22sfRP9dAakKbRbCJ+nkmNayDDqIS4nL', 'Man&Van', 'Glasgow', 'White van', 'House removals, garden clearances, single item transport', '["Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-07-14T09:26:34.037Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- robert@allinoneremovals.info
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
59, 'Robert', '07476347788', 'robert@allinoneremovals.info', 'c2NyeXB0AA4AAAAIAAAAAcnOmtkj3B2c1KCnyn4549t2vJYBr3TUvL4UujEs23bu/kQEZ+d52eDdWewF1xtLFrmOdobAOO0y4MkMsMgg8xddWwzA3uaoahOIJYRVzWCR', 'All In One Removals & Uplifts', 'G68 9NZ', 'Luton Box Van', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-17T22:12:57.121Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779055975548-inbound524488939387416810.jpg', NULL
);

-- robintrade111@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
60, 'Robin', '07554549880', 'robintrade111@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAWyWEpqfl1ErQQUhazgGsfeQFFCoRoNa1T0osL02Y57YAD3GfcQyFMzaeufcTyVe0dA95xRjUF3rIOcMAkcYJuA0E33Z+YIEFdhNUeJJfxDf', 'Eremovel', 'G42 7pn', 'Ford transit', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves"]'::jsonb, TRUE, FALSE, '2026-06-19T22:58:06.679Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781909884134-IMG_9241.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781909884713-IMG_9946.jpeg'
);

-- rr@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
61, 'Rapid Removals', '07857331890', 'rr@gmail.com', 'c2NyeXB0AA4AAAAIAAAAASKTSUauLsJkUEtXcfkqeFBM4hB6yATuOUTJ25T57b6008SBLFk6S9EkfpAjhnA22T4Emt8e+GzY0qJiKF/0h+ZjwcHAkSedDiVW+mRYZLwH', 'Rapid Removals Glasgow', 'Glasgow - UK', 'Luton LWB', 'Rapid Removals Glasgow - UK - Quick moves - Clearances - live on Callavan', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-19T19:37:08.265Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777548582269-Image%201.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777548582950-Image%202.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
61, 55.8427271806175, -4.35744027451369, 55.8427271806175, -4.35744027451369, FALSE, FALSE, NOW()
);

-- sabtain@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
62, 'test', 'test', 'sabtain@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAeVj6AiNXmYjI2TQazb4tH3/pII0XF8sI1brxmgYuiOut1jkDn3mYsdwm5UiusQnf+a0dT5O9uPhAzbK2JN4MGQ10vCbsMeYR/qAuf5/SXL2', 'test', 'test', 'test', 'test', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves"]'::jsonb, TRUE, FALSE, '2026-06-04T14:46:36.093Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1780584391920-Screenshot%202026-04-16%20183715.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1780584392794-Screenshot%202026-04-24%20201128.png'
);

-- safianhon@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
63, 'Safian', '07546970165', 'safianhon@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAaV4lDnL5bpa/Gvj8dC/Ms5v6cE9tCWWZT8OQKUPdSD0z2/7y9GMI37R6g34ev4eUfTyHUYsuihDBwggKlxZGxaLT6X/2jsoIB/1CjJG+Qr1', 'Black Van Movers', 'ML7 5FH', 'Vauxhall Vivaro', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-20T06:45:10.705Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779259509003-IMG_7120.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779259509512-IMG_7554.jpeg'
);

-- sahilthopia21@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
64, 'Sahildeep singh', '07882501149', 'sahilthopia21@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZo1EIlEM5VUjdh+NjetBx8R2p8i7K2Rh3loe1zoSH8pxvBLMbMkGvt7rbYUiqat/m3lfaDIYJQ4VI9DdNwZ+9weBPoGXHRmbKA9HC5xIOsd', 'Man with van mr singh', 'Glasgow', 'Lutton van', '', '["House Removals","Furniture Collection / Delivery","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-06-18T08:41:07.406Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781772065062-640C3789-30D8-444A-A7A7-15FF8692F763.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1781772065980-IMG_1179.jpeg'
);

-- scorotransrl@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
65, 'John', '07793561809', 'scorotransrl@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAaiKl9fnTVVuc/4jx8+4ATww5oqTC5ldSp/HSU3B6IOqa/TDUFca00sKdBVAMxjW5oN/0YaIOW+XlFg8gbH8+Gg6d+TbMCzWkJEynudzVG/f', 'Smart Move & Clearance', 'Coatbridge', 'Mercedes sprinter', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-13T13:23:12.010Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778678590528-IMG_2227.jpeg', NULL
);

-- scottmc@hotmail.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
66, 'Scott mcculloch', '07584858861', 'scottmc@hotmail.co.uk', 'c2NyeXB0AA4AAAAIAAAAATniVQVbx9EYKNiGBF40RUkjK5OFV9y3FVzrQ151jpSsRbAvcE20ZAAIxqpALpNo0a5HtYz1GdtbCvTm7Ms8a+y9JEQn8hBJa7R//8TS9Aiv', 'Mearns removals ltd', 'Barrhead', 'Ford transit cage tipper', '', '["Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-08-20T12:28:20.887Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1787228899005-25876.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1787228899477-37264.jpg'
);

-- sebekglasgow@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
67, 'Sebastian Żero', '07864880589', 'sebekglasgow@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAd+XRimnqjyerPAGBaQNI28v4HuUpiiS1Nw3mvTNN1Coonpm35vXD0KWQjkhOISbQ+aGfLrQv7gvHeBkd0yefg93bqtjslvFVx64ywhLNGKI', 'Self employed', 'G52', 'Renault master', '', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-16T13:17:33.563Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778937451206-IMG_5598.jpeg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1778937451830-IMG_6083.jpeg'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
67, 55.8516088976352, -4.36790109501982, 55.8516088976352, -4.36790109501982, FALSE, FALSE, NOW()
);

-- stegasauras89@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
68, 'Stefan Smith', '07955995353', 'stegasauras89@gmail.com', 'c2NyeXB0AA4AAAAIAAAAATv0c+B+S/QsTReK7caoh61FS8IJ8vKv1kokuQtSJN1Jx3cXn4KgMGKlyIbIlSkjgNKnZ2MzrgUThj47YHCxb7fxzifNCKXEAT1xgKJXkZHT', 'Removal Man', 'Glasgow', 'Luton van', 'Over 7 years experience in the removals industry.', '["Waste / Disposal Runs","House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-05-02T09:33:44.232Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777714422257-Professional%20Home%20Removal%20Services%20Poster.png', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1777714422968-Professional%20Home%20Removal%20Services%20Poster.png'
);

INSERT INTO driver_locations (
  driver_id, latitude, longitude, offline_latitude, offline_longitude,
  is_live, is_logged_in, last_active
) VALUES (
68, 55.8597016491314, -4.13181027922846, 55.8597016491314, -4.13181027922846, FALSE, FALSE, NOW()
);

-- stuart@chapter5solutions.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
69, 'Stuart Douglas Handy', '07976555557', 'stuart@chapter5solutions.co.uk', 'c2NyeXB0AA4AAAAIAAAAATRFTLWwZo64WQhFCrBNYZMvfRhyT98fRaF9wpg3vrtyX5rHffUwGdRIyJ0w56bMBprVJ4L6ToS0GXRWFU0CvxLFWgtOJAXXoI+ajDWhxubO', 'allmac scotland', 'glasgow', 'luton van', 'MAN AND A VAN🚚 ✔️Single and multiple items ✔️Part and full house moves ✔️Shop pick ups from Ikea and B&Q etc ✔️Office moves', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, FALSE, FALSE, '2026-04-23T10:17:14.848Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776939432315-250C72D8-68FC-4F62-82EA-4A4AB12C2816.PNG', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1776939432949-250C72D8-68FC-4F62-82EA-4A4AB12C2816.PNG'
);

-- stubhoy@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
70, 'Stuart MONTGOMERY', '07887690047', 'stubhoy@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAa80Xh6iarhIljxvvJEMnBZnRwSImBTb7BDTObA/epp4x0bgc/l4hljmyGpP55jiraUiZZwR9ApZC204uZDv+qlRyeCd2xMbrf//NX4Bz0VX', 'Montys Man & Van Services', 'Glasgow', 'Ford Transit', '', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-08-25T16:28:18.962Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1787675297244-90879.png', NULL
);

-- stubhoy426@yahoo.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
71, 'Stewart gilgallon', 'Stewart gilgallon', 'stubhoy426@yahoo.com', 'c2NyeXB0AA4AAAAIAAAAAYxFUYP+DK+VMTjgbuRWX7l6FXLAyrCsWRCdL+lswP4R68aOYjZnXVtD6HPDklnWdqvKURqd6ELCVTGItr5HkugJBLFd7cQ0Qrz8ogJjmtQc', 'Only vans sameday ltd', 'G72 9AG', 'Jumbo transit and luton van', '07903757038', '["House Removals","Single Item Transport","Furniture Collection / Delivery","Storage Moves","Small Moves / Student Moves","Waste / Disposal Runs"]'::jsonb, TRUE, FALSE, '2026-05-19T16:14:43.895Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779207281030-inbound5206364888861518465.jpg', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779207281708-inbound3875871343285909900.jpg'
);

-- t.k.removals1@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
72, 'Tomasz', '07751613470', 't.k.removals1@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZ4/bJbIXNDqjqo8Jo6Y8+fBgreNvjCm2GzGoFCFsnOjOtXcuMlYYZ8XN3NPpGArszGbzeHL6pZZU1SQ7kgtW/ddgfs0GSImbcH7rL3xnDkl', 'T.K.Removals', 'Edinburgh-Glasgow-all Scotland and U.K.', 'Movano L3H2', 'I offer transport and packing services in a team of 1-2 people. Accurate, safe, and hassle-free. Pickup from B&M, Ikea, B&Q, Jewson, Screwfix, TOOLSTATION, and Marketplace.', '["House Removals","Storage Moves","Small Moves / Student Moves","Furniture Collection / Delivery","Single Item Transport"]'::jsonb, TRUE, FALSE, '2026-05-18T14:38:00.100Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/1779115078825-IMG_3743.jpeg', NULL
);

-- test@123.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
73, 'test', '0000000000', 'test@123.com', 'c2NyeXB0AA4AAAAIAAAAARFpkl6Gao3P7DBwbk5QjeqyqeLGhsqdIRNZqr/WKZhpPfEGpOzURpcnfBL/IgoyKJ0ofhYD102FCqxrF++i17VU5msr0q8dr846Z8Hltvuw', NULL, NULL, NULL, '', '[]'::jsonb, FALSE, FALSE, '2026-05-18T20:10:19.864Z', NULL, NULL
);

-- testing@qq.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
74, 'testing', '0000000000', 'testing@qq.com', 'c2NyeXB0AA4AAAAIAAAAAS0/B/Ve84kgXjmj8t2URTdL8biK57GckJTzAG5ScMc0vrFpTFINV2vgVYhQO4IQQUXp3QCdmaFOHMeYtwJquyRdpm+Z7mGlnh9czrv0D3gb', NULL, NULL, NULL, '', '[]'::jsonb, FALSE, FALSE, '2026-05-18T20:43:47.237Z', NULL, NULL
);

-- tt@rr.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
75, 'tt', '0000000000', 'tt@rr.com', 'c2NyeXB0AA4AAAAIAAAAAYNehgvBmKyjyqaOzxjJ6Ug4vUSmtZXSXs5hEawzzeebU0jdu/ppkDvR7XL3XldXuv7gxkQWSSPP3FKT+xxSnqNXdiZ/2lc1uxyCy33r5xxZ', NULL, NULL, NULL, '', '[]'::jsonb, FALSE, FALSE, '2026-05-18T20:42:46.014Z', NULL, NULL
);

-- zg@gmail.com
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
76, 'jzknsxcjk', '07738092443', 'zg@gmail.com', 'c2NyeXB0AA4AAAAIAAAAAZen8wCbBT3eOFDCCp6GA0v8tXpVntCRppbyXzm5CElQN/byEqBJixUMTMCIxzNrfeXXx1G1bkQKm75LntTw3/m1AIAYupo/zYA9dLIJUlFt', 'dfcdfv', 'dffdvf', 'cfdvcf', 'vfevfv', '["House Removals","Furniture Collection / Delivery"]'::jsonb, FALSE, FALSE, '2026-08-13T08:40:09.293Z', 'https://aohtsangszwfshfytwke.supabase.co/storage/v1/object/public/Driver%20Images/images/ec9a73dc-c385-4298-9adc-74f4a1143ee9.png', NULL
);

-- zg@yahoo.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
77, 'zg', '0000000000', 'zg@yahoo.co.uk', 'c2NyeXB0AA4AAAAIAAAAAWkjYh9/Gv0ghjD3wxib3lSCzWPH14TxNv5O8gwa0nLX6axItjh9TRF1FH00CmzGUCp3A6gEwhGRTClEkyuC2PJnjXYSgoiZsQPxRHeFONTf', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-04-01T08:41:47.785Z', NULL, NULL
);

-- zg1210@yahoo.co.uk
INSERT INTO drivers (
  id, full_name, mobile_number, email, password_hash,
  company_name, base_area, vehicle_type, short_bio, services_offered,
  is_approved, is_live, created_at, profile_image_url, van_image_url
) VALUES (
78, 'zg1210', '0000000000', 'zg1210@yahoo.co.uk', 'c2NyeXB0AA4AAAAIAAAAAYCKsGMnX7r/PxW1uB6E3n9MJRd/WVGnyrfDpDBkYsaF/2G20xSKv/kmiqekVJ+nSCQ9zaBFrXR7b/4nIZ65PRqTGKX8awbdYKZNi3MKuZ6h', NULL, NULL, NULL, '', '[]'::jsonb, TRUE, FALSE, '2026-03-25T19:24:12.868Z', NULL, NULL
);

SELECT setval(pg_get_serial_sequence('drivers', 'id'), (SELECT COALESCE(MAX(id), 1) FROM drivers));

COMMIT;
